server:
  port: 9005
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/mydata/SadTalker/results/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.33.239.2:3306/phototovideo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://106.75.97.89:3306/phototovideo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hzz123QWE
    hikari:
      max-lifetime: 60000

logging:
  level:
    root: INFO

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0

# The callback address
modelUrl: http://127.0.0.1:9005/videoDetails/v1/modelHandling

# Storage path
#resultDir: E:\vieds
resultDir: /mydata/SadTalker/results

#localhostApi: http://127.0.0.1:9005/
localhostApi: http://106.75.97.89:9005/

#generateVideoUrl: http://127.0.0.1:5000/generate_video
generateVideoUrl: http://106.75.97.89:5000/generate_video